twheels/core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^book/$',views.book, name='book'),
	url(r'^booki/$',views.booki, name='booki'),
	url(r'^manage/$',views.managetrans, name='managetrans')
]

twheels/wheels/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^core/',include('core.urls',namespace="core")),
]

twheels/core/models.py
from django.db import models

class Bike(models.Model):
	def __str__(self):
		return self.bike_model+str((self.depl_date))
	bike_model = models.CharField(max_length=200)
	depl_date = models.DateTimeField('Date Deployed')
	position_x = models.FloatField()
	position_y = models.FloatField()

class Customer(models.Model):
	def __str__(self):
		return self.name+' '+str(self.pan_id)
	pan_id = models.IntegerField(primary_key=True)
	name = models.CharField(max_length = 100)
	mem_join = models.DateTimeField('Date Joined')

class Transaction(models.Model):
	def __str__(self):
		return str(self.id)
	bike = models.ForeignKey(Bike)
	cust = models.ForeignKey(Customer)
	start_time = models.DateTimeField()
	end_time = models.DateTimeField(null=True,blank=True)
	rate = models.IntegerField(default=10)
	
class Station(models.Model):
	name = models.CharField(default='Name',max_length=100)
	coordinates_x = models.FloatField()
	coordinates_y = models.FloatField()
	Incharge = models.CharField(max_length=100)

twheels/core/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Transaction,Bike,Station,Customer
from django.utils import timezone
from django.core.urlresolvers import reverse
 

def index(request):
	latest_transaction_list = Transaction.objects.order_by('-start_time')[:5]
	context = {'latest_transaction_list':latest_transaction_list}
	return render(request,'core/index.html',context)

def book(request):
	available_bikes = Bike.objects.all()
#	stations = Station.objects.all()
	customers = Customer.objects.all()
	context = { 'available_bikes' : available_bikes ,'customers':customers}
	return render(request, 'core/book.html',context)

def booki(request):
	bk = Bike.objects.get(id=request.POST['choice_bike'])
	cs = Customer.objects.get(pan_id=request.POST['choice_customer'])
	#st = Station.objects.get(id=request.POST['choice_station'])
	new_transaction = Transaction(bike=bk,cust=cs,start_time=timezone.now())
	new_transaction.save()
	return HttpResponseRedirect(reverse('core:index'))

def managetrans(request):
	trans = Transaction.objects.filter(end_time=None)
	context = { 'active_transactions' : trans }
	return render(request,'core/managetrans.html',context)

twheels/core/templates/core/book.html
<h1>Make a Booking here!</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'core:booki' %}" method="post">
	{% csrf_token %}
	Select Bike</br>
	<select>
	{% for bike in available_bikes %}
	    <option name="choice_bike" id="choice{{ forloop.counter }}" value="{{ bike.id }}" />
	    <label for="choice{{ forloop.counter }}">{{ bike.bike_model }}</label></option>
		{% endfor %}
	</select><br/>
		Select Station</br>
	{% for station in stations %}
	    <input type="radio" name="choice_station" id="choice{{ forloop.counter }}" value="{{ station.id }}" />
	        <label for="choice{{ forloop.counter }}">{{ station.name }}</label><br />
		{% endfor %}
		Select Customer</br>
	{% for customer in customers %}
	    <input type="radio" name="choice_customer" id="choice{{ forloop.counter }}" value="{{ customer.pan_id }}" />
	        <label for="choice{{ forloop.counter }}">{{ customer }}</label><br />
		{% endfor %}
		<input type="submit" value="Book" />
</form>

twheels/core/templates/core/index.html
<h1>Welcome to the Wheels Website!</h1>
<p>
{% if latest_transaction_list %}
<table>
	<tr>
		<td>ID</td>
		<td>Start Time</td>
		<td>End Time</td>
		<td>Bike</td>
		<td>Rate</td>
		<td>Customer</td>
	</tr>
	{% for transaction in latest_transaction_list %}
	<tr>
		<td>{{transaction.id}}</td>
		<td>{{transaction.start_time}}</td>
		<td>{{transaction.end_time}}</td>
		<td>{{transaction.bike}}</td>
		<td>{{transaction.rate}}</td>
		<td>{{transaction.cust.pan_id}}</td>
	</tr>
	{% endfor %}
{% else %}
	<p>No transactions to show</p>
{% endif %}

twheels/core/templates/core/managetrans.html
<h1>Manage Ongoing Transactions<br/></h1>
<form action="{% url 'core:endtrip'%}" method="post">
<table>
<tr>
	<td>id</td>
	<td>start_time</td>
	<td>bike</td>
	<td>cust</td>
	<td>rate</td>
</tr>
{% for transaction in active_transactions %}
<tr>
	<td>{{transaction.id}}</td>
	<td>{{transaction.start_time}}</td>
	<td>{{transaction.bike}}</td>
	<td>{{transaction.cust}}</td>
	<td>{{transaction.rate}}</td>
	<td><input type="radio" name</td>
</tr>
{% endfor %}
</table>
<input type="submit" value="End Trip" /></form>